Refactor `flake.nix`
NilFoundation/zkEVM-framework pull request #81
Opened 2024-07-19 13:47 UTC by aleasims

Some refactoring of flake file:

- Move derivation into separate file, simplify flake file;
- Removed explicit dev shells from flake file
- Remove unnecessary step in CI workflow;
- Remove `flake-utils` from Crypto3 input (because it's not used in the current revision of Crypto3).

Most of the things work the same as previously. To activate dev debug shell, run:

```
nix develop .#debug
```

Some things which may be improved in the future:
- Refine Boost library propagation properly
- Refine the list of required Go tools (they were just copy-pasted, probably we don't need all of them)

2024-07-19 14:49 UTC, aleasims commented
Also created targets in CMake for testing executables (block generator and assigner) runs on example data. To run these tests:

```
ninja executables_tests
```

This will compile required binaries (`assigner`, `block_gen`, ...) and run them with specified inputs.

This will allow us to run all tests inside single test derivation via Nix and avoid re-compilation of the whole derivation (CI time will decrease).

2024-07-19 14:56 UTC, aleasims commented
@knazarov could you please take a look at Nix part of this PR

2024-07-22 07:11 UTC, akokoshn approved these changes

2024-07-22 10:24 UTC, AndreyMlashkin requested changes

2024-07-22 10:24 UTC, AndreyMlashkin commented on flake.nix
>        crypto3 = nil-crypto3.packages.${system}.default;
use crypto3 = nil-crypto3.packages.${system}.crypto3; here

2024-07-22 10:25 UTC, AndreyMlashkin commented on flake.nix
>        crypto3 = nil-crypto3.packages.${system}.default;
it runs crypto3 tests on the first run now

2024-08-07 19:40 UTC, x-mass approved these changes
LGTM, except we there is no way to `nix develop` into debug with tests. Are we sure we don't want to make default check use Debug build? In this case it could be used as a target for `nix develop`. Or just return back devShells with debug+tests configuration

2024-08-28 08:24 UTC, akokoshn commented
moved to https://github.com/NilFoundation/zkEVM-framework/pull/84

2024-08-28 08:24 UTC, closed without merging